disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - discarded_notification_center_observer
  - multiple_closures_with_trailing_closure
  - identifier_name
  - todo
included: # paths to include during linting. `--path` is ignored if present.
  - garbageCollection
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - garbageCollection/External
line_length: 180
large_tuple:
   warning: 3
   error: 4
nesting:
  type_level: 2
force_cast: warning
